### ISSUE TITLE
Build Mission Model 1 - Coral Nursery

### ISSUE THREAD

**Issue by dsplaisted** [wccarobotics/submerged#1]
![image](https://github.com/user-attachments/assets/ec6eaf8b-3ab2-4df2-aea7-647511ecc184)

## Building Instructions

**Bags 1 and 2**

https://firstinspires.blob.core.windows.net/fll/challenge/2024-25/fll-challenge-submerged-bi-book-1-enus.pdf

https://www.fllcasts.com/materials/2202-coral-nursery-bags-1-and-2-first-lego-league-2024-2025-submerged

**Comment by lsplaisted** [comment]
Hello how are you?

**Comment by dsplaisted** [comment]
Built by Leo, Weston, Joseph.
