### ISSUE TITLE
Robot Design Brainstorming - Create

### ISSUE THREAD

**Issue by dsplaisted** [wccarobotics/submerged#25]
Team developed original designs or improved on existing ones according to their mission strategy

- Clear explanation of innovative attachments and their purpose
- Clear explanation of innovative code and/or sensor use

**Comment by williamruizcisneros** [comment]
ello

**Comment by phanaelahdessource** [comment]
HAII

**Comment by nathaneald** [comment]
we should make slick attachments

**Comment by rogeliocarty** [comment]
> we should make slick attachments

wym?

**Comment by josephcaballerocastillo** [comment]
what do u mean

**Comment by williamruizcisneros** [comment]
@nathaneald naaaaaaaaaah

**Comment by paytonestrada** [comment]
_we are going to have to push pull and some more_

**Comment by phanaelahdessource** [comment]
like i said. GLITTER.

**Comment by williamruizcisneros** [comment]
what should we make though

**Comment by lsplaisted** [comment]
Everyone shows what each attachment does.
@phanaelahdessource no arguing about bordom

**Comment by phanaelahdessource** [comment]
> _we are going to have to push pull and some more_

wt

**Comment by phanaelahdessource** [comment]
> Everyone shows what each attachment does. @phanaelahdessource no arguing about bordom

aw man :(

**Comment by williamruizcisneros** [comment]
SHUT UP ABT THE GLITTER

**Comment by rogeliocarty** [comment]
> we should make slick attachments
 like thin attachments?

**Comment by alexvasquezandino** [comment]
we should tell what things do for the mission models

**Comment by nathaneald** [comment]
> SHUT UP ABT THE GLITTER

calm down calm down

**Comment by paytonestrada** [comment]
_we should make one attachment for each one like pushing pulling and the others_

**Comment by williamruizcisneros** [comment]
what attachment should we make for the boat dude

**Comment by CWOcean** [comment]
> > we should make slick attachments
> > like thin attachments?
what does "slick" mean?

**Comment by nathaneald** [comment]
> _we should make one attachment for each one like pushing pulling and the others_

and that goes up and down

**Comment by williamruizcisneros** [comment]
@nathaneald no >:(

**Comment by lsplaisted** [comment]
Explain why we did/didn't use sensors.

**Comment by phanaelahdessource** [comment]
> SHUT UP ABT THE GLITTER
that hurts my feewings :(

**Comment by nathaneald** [comment]
> > > we should make slick attachments
> > > like thin attachments?
> > > what does "slick" mean?

uuh like that can come off easily

**Comment by williamruizcisneros** [comment]
@nathaneald yes yes!

**Comment by phanaelahdessource** [comment]
sensors were too hard to put on

**Comment by josephcaballerocastillo** [comment]
yeah but it will be hard to do a attachment for the boat for that one we should work in teamwork

**Comment by phanaelahdessource** [comment]
> > > > we should make slick attachments
> > > > like thin attachments?
> > > > what does "slick" mean?
> 
> uuh like that can come off easily

true that

**Comment by nathaneald** [comment]
> sensors were too hard to put on

no we just didnt code it bro

**Comment by alexvasquezandino** [comment]
> yeah but it will be hard to do a attachment for the boat for that one we should work in teamwork

true

**Comment by paytonestrada** [comment]
the boat is not that hard

**Comment by phanaelahdessource** [comment]
> > sensors were too hard to put on
> 
> no we just didnt code it bro

okayyyyy

**Comment by lsplaisted** [comment]
Show interesting parts of code.

**Comment by alexvasquezandino** [comment]
@lsplaisted yes

**Comment by nathaneald** [comment]
> Show interesting parts of code.

like complex ones?

**Comment by josephcaballerocastillo** [comment]
than do a attachemnt payton for the the boat that will be helpful

**Comment by phanaelahdessource** [comment]
> the boat is not that hard

yeah @josephcaballerocastillo

**Comment by williamruizcisneros** [comment]
> like complex ones?

yes

**Comment by nathaneald** [comment]
> > like complex ones?
> 
> yes

i asked lucas

**Comment by nathaneald** [comment]
> > > like complex ones?
> > 
> > 
> > yes
> 
> i asked lucas

but whatever

**Comment by williamruizcisneros** [comment]
> i asked lucas

idc

**Comment by phanaelahdessource** [comment]
> than do a attachemnt payton for the the boat that will be helpful

then you can do it becuz ur recommending it

**Comment by williamruizcisneros** [comment]
okay then but what about the crab cage

**Comment by josephcaballerocastillo** [comment]
ok i will truy

**Comment by josephcaballerocastillo** [comment]
i mean try

**Comment by williamruizcisneros** [comment]
> okay then but what about the crab cage

its very hard to do

**Comment by phanaelahdessource** [comment]
i aint got time to improve no robot

**Comment by alexvasquezandino** [comment]
we should all trust each other to do stuff

**Comment by williamruizcisneros** [comment]
> we should all trust each other to do stuff

what stuff dawg???

**Comment by phanaelahdessource** [comment]
> we should all trust each other to do stuff

YAYYY!!!FRIENDSHIP!!!!!

**Comment by CWOcean** [comment]
We should build our own robot and attachments, so we get extra points for innovation instead of looking up videos online

**Comment by lsplaisted** [comment]
> i aint got time to improve no robot

Read Qotd#21 @phanaelahdessource

**Comment by phanaelahdessource** [comment]
> > i aint got time to improve no robot
> 
> Read Qotd#21 @phanaelahdessource

GG

**Comment by nathaneald** [comment]
> i aint got time to improve no robot

we need to improve the robot

>> yeah

**Comment by williamruizcisneros** [comment]
HOW SHOULD WE DO THE CRAB CAGE AND DO IT PERFECT?!?!??

**Comment by paytonestrada** [comment]
more then one person can do the same model

**Comment by alexvasquezandino** [comment]
@williamruizcisneros like trusting that the build stuff and do some coding for the robot

**Comment by phanaelahdessource** [comment]
> We should build our own robot and attachments, so we get extra points for innovation instead of looking up videos online

true,true

**Comment by nathaneald** [comment]
> more then one person can do the same model

or we need team work

**Comment by rogeliocarty** [comment]
groups of 3-4

**Comment by williamruizcisneros** [comment]
> @williamruizcisneros like trusting that the build stuff and do some coding for the robot

i mean like an attachment and coding

**Comment by phanaelahdessource** [comment]
> @williamruizcisneros like trusting that the build stuff and do some coding for the robot

wdym

**Comment by lsplaisted** [comment]
Explain what we changed if we copied something.

**Comment by westonestrada** [comment]
> > We should build our own robot and attachments, so we get extra points for innovation instead of looking up videos online
> 
> true,true

**Comment by paytonestrada** [comment]
> > more then one person can do the same model
> 
> or we need team work

ww can do both

**Comment by nathaneald** [comment]
> groups of 3-4

🧐
we should assign an attachment to each group

**Comment by williamruizcisneros** [comment]
> > > We should build our own robot and attachments, so we get extra points for innovation instead of looking up videos online
> > 
> > 
> > true,true

bro your gonna make a wall 😭🙏

**Comment by alexvasquezandino** [comment]
> > @williamruizcisneros like trusting that the build stuff and do some coding for the robot
> 
> i mean like an attachment and coding

something like that @williamruizcisneros

**Comment by phanaelahdessource** [comment]
> 🧐

and

> > > > We should build our own robot and attachments, so we get extra points for innovation instead of looking up videos online
> > > 
> > > 
> > > true,true
> 
> bro your gonna make a wall 😭🙏

and ur helping us

**Comment by williamruizcisneros** [comment]
> > > @williamruizcisneros like trusting that the build stuff and do some coding for the robot
> > 
> > 
> > i mean like an attachment and coding
> 
> something like that @williamruizcisneros

fr fr

**Comment by phanaelahdessource** [comment]
> > > @williamruizcisneros like trusting that the build stuff and do some coding for the robot
> > 
> > 
> > i mean like an attachment and coding
> 
> something like that @williamruizcisneros

ohhhhh

**Comment by nathaneald** [comment]
bro we need to learn to do the sensors bro

**Comment by westonestrada** [comment]
> > > > @williamruizcisneros like trusting that the build stuff and do some coding for the robot
> > > 
> > > 
> > > i mean like an attachment and coding
> > 
> > 
> > something like that @williamruizcisneros
> 
> ohhhhh

**Comment by phanaelahdessource** [comment]
> > > > @williamruizcisneros like trusting that the build stuff and do some coding for the robot
> > > 
> > > 
> > > i mean like an attachment and coding
> > 
> > 
> > something like that @williamruizcisneros
> 
> ohhhhh

i still dont get it

**Comment by alexvasquezandino** [comment]
womp womp lil brain

**Comment by phanaelahdessource** [comment]
the sensors are trippin tho

**Comment by paytonestrada** [comment]
> bro we need to learn to do the sensors bro

the sensors can be hard to do for some people

**Comment by williamruizcisneros** [comment]
> i still dont get it
 me too :(

**Comment by josephcaballerocastillo** [comment]
:                                                                    )

**Comment by phanaelahdessource** [comment]
> womp womp lil brain

like u can be talking

**Comment by williamruizcisneros** [comment]
> ```
>                                                                                                                           :                                                                    )
> ```

whywhy

**Comment by alexvasquezandino** [comment]
i can

**Comment by rogeliocarty** [comment]
> > womp womp lil brain
> 
> like u can be talking

alex has gave no ideas 🥶

**Comment by phanaelahdessource** [comment]
> ```
>                                                                                                                           :                                                                    )
> ```

whats the point of this

**Comment by alexvasquezandino** [comment]
????

**Comment by williamruizcisneros** [comment]
> > > womp womp lil brain
> > 
> > 
> > like u can be talking
> 
> alex has gave no ideas 🥶

sadly

**Comment by paytonestrada** [comment]
> > ```
 hiw> >                                                                                                                           :                                                                    )
> > ```
> 
> whats the point of this

idk

**Comment by phanaelahdessource** [comment]
> > > womp womp lil brain
> > 
> > 
> > like u can be talking
> 
> alex has gave no ideas 🥶

where are yall finding the emojis??

**Comment by nathaneald** [comment]
> > > > womp womp lil brain
> > > 
> > > 
> > > like u can be talking
> > 
> > 
> > alex has gave no ideas 🥶
> 
> sadly

dont make a wall on

**Comment by josephcaballerocastillo** [comment]
guys stop

**Comment by phanaelahdessource** [comment]
> > > > > womp womp lil brain
> > > > 
> > > > 
> > > > like u can be talking
> > > 
> > > 
> > > alex has gave no ideas 🥶
> > 
> > 
> > sadly
> 
> dont make a wall

y

**Comment by rogeliocarty** [comment]
i probably missed his ideas

**Comment by alexvasquezandino** [comment]
@rogeliocarty i ha ve been giving ideas

**Comment by paytonestrada** [comment]
he has no ideas

**Comment by westonestrada** [comment]
> > > > > womp womp lil brain
> > > > 
> > > > 
> > > > like u can be talking
> > > 
> > > 
> > > alex has gave no ideas 🥶
> > 
> > 
> > sadly
> 
> dont make a wall on

**Comment by nathaneald** [comment]
how crab cage

> ye

**Comment by josephcaballerocastillo** [comment]
stop the cap how

**Comment by rogeliocarty** [comment]
womp


> @rogeliocarty i ha ve been giving ideas

good 👍

**Comment by williamruizcisneros** [comment]
> how crab cage
> 
> > ye

how could you code it nathan?

**Comment by alexvasquezandino** [comment]
> stop the cap

dawg so trusting each other not a idea?????? ee sddes s

**Comment by westonestrada** [comment]
> > stop the cap
> 
> dawg so trusting each other not a idea??????

nooooooooooooo

**Comment by williamruizcisneros** [comment]
> > stop the cap
> 
> dawg so trusting each other not a idea??????

it isnt ._.

**Comment by paytonestrada** [comment]
👌

**Comment by phanaelahdessource** [comment]
how do we even do the crab cage

**Comment by nathaneald** [comment]
You could just do a ai attachment

**Comment by westonestrada** [comment]
> 👌

why

**Comment by nathaneald** [comment]
> 👌

![OIP (7)](https://github.com/user-attachments/assets/fbf61ef5-c327-4627-b93c-feafdbfbb3f3)

**Comment by phanaelahdessource** [comment]
WHERE ARE YOU?!

**Comment by paytonestrada** [comment]
stopp👌👌 nice

**Comment by williamruizcisneros** [comment]
no

**Comment by williamruizcisneros** [comment]
g

**Comment by phanaelahdessource** [comment]
WHERE ARE YOU GUYS FINDING THE EMOJIS?!?!?!?!

**Comment by paytonestrada** [comment]
x

> WHERE ARE YOU GUYS FINDING THE EMOJIS?!?!?!?!

somewhere

**Comment by williamruizcisneros** [comment]
nope

**Comment by nathaneald** [comment]
windows + .

**Comment by phanaelahdessource** [comment]
> x
> 
> > WHERE ARE YOU GUYS FINDING THE EMOJIS?!?!?!?!
> 
> somewhere
😒

**Comment by rogeliocarty** [comment]
do : and then like sob or smth phanel

**Comment by phanaelahdessource** [comment]
PEACE OUT CHAT✌

**Comment by paytonestrada** [comment]
BYEEE

**Comment by rogeliocarty** [comment]
end igngldkcjnl ,dxmrz.gmb[ksnxf.m;dmx/,fnh 😎

**Comment by westonestrada** [comment]
stop

**Comment by nathaneald** [comment]
ok

**Comment by alexvasquezandino** [comment]
nuh uh

**Comment by phanaelahdessource** [comment]
![Image](https://github.com/user-attachments/assets/cb0a0db3-cc40-471b-8bb7-4918fa9051a2)
