### ISSUE TITLE
Build Mission Model 3 - Shark

### ISSUE THREAD

**Issue by dsplaisted** [wccarobotics/submerged#3]
![image](https://github.com/user-attachments/assets/2b7ca04b-3cf3-4117-9490-ae2ce93bb7c4)

## Building Instructions

**Bags 5, 6, and 7**

https://firstinspires.blob.core.windows.net/fll/challenge/2024-25/fll-challenge-submerged-bi-book-3-enus.pdf

https://www.fllcasts.com/materials/2207-shark-bags-5-6-and-7-first-lego-league-2024-2025-submerged

**Comment by lsplaisted** [comment]
I want to do this one.

**Comment by rogeliocarty** [comment]
5 , 6 and 7
