### ISSUE TITLE
Stop posting images in the chat

### ISSUE THREAD

**Issue by lsplaisted** [wccarobotics/submerged#41]
Stop posting images in the chat!

**Comment by rogeliocarty** [comment]
ok

**Comment by rogeliocarty** [comment]
i dont though

**Comment by josephcaballerocastillo** [comment]
hello

**Comment by nathaneald** [comment]
i dont either

**Comment by alexvasquezandino** [comment]
ME EITHER

**Comment by phanaelahdessource** [comment]
![Image](https://github.com/user-attachments/assets/429beed0-2f4d-408a-9717-dd32b7cc3e9b)

**Comment by phanaelahdessource** [comment]
![Image](https://github.com/user-attachments/assets/8bcc6f37-fa9e-4ddd-a54c-3ff42794b2fe)

**Comment by rogeliocarty** [comment]
hi

**Comment by nathaneald** [comment]
scrathc
- scratch
- mathc
-

**Comment by rogeliocarty** [comment]
**jnvbhjk**
