### ISSUE TITLE
Build Mission Model 6 - Raise the Mast and Kraken's Treasure

### ISSUE THREAD

**Issue by dsplaisted** [wccarobotics/submerged#6]
![image](https://github.com/user-attachments/assets/0f3594fa-90ee-4921-b0f3-d677efb907b3)

![image](https://github.com/user-attachments/assets/de847ea0-97e3-406e-a171-2d0b11a2dfbd)

## Building Instructions

**Bags 12 and 13**

https://firstinspires.blob.core.windows.net/fll/challenge/2024-25/fll-challenge-submerged-bi-book-6-enus.pdf

https://www.fllcasts.com/materials/2231-raise-the-mast-bags-12-and-13-first-lego-league-2024-2025-submerged?ref=14168

**Comment by dsplaisted** [comment]
Built by Alex, Diego, Payton

**Comment by rogeliocarty** [comment]
and me!!
