### ISSUE TITLE
Build Mission Model 9 - Send Over the Submersible

### ISSUE THREAD

**Issue by dsplaisted** [wccarobotics/submerged#9]
![image](https://github.com/user-attachments/assets/0ab1fe91-078d-4e01-a220-3706473749d5)

## Building Instructions

**Bags 18, 19, and 20**

https://firstinspires.blob.core.windows.net/fll/challenge/2024-25/fll-challenge-submerged-bi-book-9-enus.pdf

https://www.fllcasts.com/materials/2203-send-over-the-submersible-bags-18-19-and-20-first-lego-league-2024-2025-submerged

**Comment by lsplaisted** [comment]
done.
